/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module FBUC(PI, CLK, reset, ld, cnt, Ci, PO, Co);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  input CLK;
  input Ci;
  output Co;
  input PI;
  output [3:0] PO;
  reg [3:0] PO;
  input cnt;
  input ld;
  input reset;
  NOT _58_ (
    .A(_29_),
    .Y(_35_)
  );
  NOT _59_ (
    .A(_34_),
    .Y(_36_)
  );
  NOT _60_ (
    .A(_30_),
    .Y(_37_)
  );
  NOT _61_ (
    .A(_32_),
    .Y(_38_)
  );
  NAND _62_ (
    .A(_26_),
    .B(_33_),
    .Y(_39_)
  );
  NOT _63_ (
    .A(_39_),
    .Y(_40_)
  );
  NOR _64_ (
    .A(_35_),
    .B(_39_),
    .Y(_41_)
  );
  NOT _65_ (
    .A(_41_),
    .Y(_42_)
  );
  NOR _66_ (
    .A(_29_),
    .B(_40_),
    .Y(_43_)
  );
  NOR _67_ (
    .A(_41_),
    .B(_43_),
    .Y(_44_)
  );
  NOR _68_ (
    .A(_34_),
    .B(_44_),
    .Y(_45_)
  );
  NOR _69_ (
    .A(_28_),
    .B(_36_),
    .Y(_46_)
  );
  NOR _70_ (
    .A(_45_),
    .B(_46_),
    .Y(_22_)
  );
  NOR _71_ (
    .A(_37_),
    .B(_42_),
    .Y(_47_)
  );
  NAND _72_ (
    .A(_30_),
    .B(_41_),
    .Y(_48_)
  );
  NOR _73_ (
    .A(_30_),
    .B(_41_),
    .Y(_49_)
  );
  NOR _74_ (
    .A(_34_),
    .B(_49_),
    .Y(_50_)
  );
  NAND _75_ (
    .A(_48_),
    .B(_50_),
    .Y(_51_)
  );
  NOT _76_ (
    .A(_51_),
    .Y(_23_)
  );
  NAND _77_ (
    .A(_31_),
    .B(_47_),
    .Y(_52_)
  );
  NOR _78_ (
    .A(_31_),
    .B(_47_),
    .Y(_53_)
  );
  NOR _79_ (
    .A(_34_),
    .B(_53_),
    .Y(_54_)
  );
  NAND _80_ (
    .A(_52_),
    .B(_54_),
    .Y(_55_)
  );
  NOT _81_ (
    .A(_55_),
    .Y(_24_)
  );
  NOR _82_ (
    .A(_38_),
    .B(_52_),
    .Y(_27_)
  );
  NAND _83_ (
    .A(_38_),
    .B(_52_),
    .Y(_56_)
  );
  NAND _84_ (
    .A(_36_),
    .B(_56_),
    .Y(_57_)
  );
  NOR _85_ (
    .A(_27_),
    .B(_57_),
    .Y(_25_)
  );
  always @(posedge CLK or posedge reset)
    if (reset)
      PO[0] <= 0;
    else
      PO[0] <= _00_[0];
  always @(posedge CLK or posedge reset)
    if (reset)
      PO[1] <= 0;
    else
      PO[1] <= _00_[1];
  always @(posedge CLK or posedge reset)
    if (reset)
      PO[2] <= 0;
    else
      PO[2] <= _00_[2];
  always @(posedge CLK or posedge reset)
    if (reset)
      PO[3] <= 0;
    else
      PO[3] <= _00_[3];
  assign _26_ = Ci;
  assign _29_ = PO[0];
  assign _33_ = cnt;
  assign _28_ = PI;
  assign _34_ = ld;
  assign _00_[0] = _22_;
  assign _30_ = PO[1];
  assign _00_[1] = _23_;
  assign _31_ = PO[2];
  assign _00_[2] = _24_;
  assign _32_ = PO[3];
  assign _00_[3] = _25_;
  assign Co = _27_;
endmodule
